### ISSUE TITLE
Failed build duo to wrong h5py

### ISSUE THREAD

**Issue by QwZhang** [underworldcode/underworld2#107]
Hi all,
I have been trying to migrate to UW2 and I built the source code of lastest UW2 release (underworld2-2.0.3b) today on Mac OS X 10.11 but failed:
```bash
./configure.py --hdf5-dir=/opt/local/hdf5-1.10.0 --petsc-dir=/opt/local/petsc-3.4.5
fatal: Not a git repository (or any of the parent directories): .git
scons: Reading SConscript files ...
Checking whether the C compiler worksyes
Checking for Solvers... yes
Checking for package libm... yes
Checking for package libXML2... yes
Checking for package MPI... yes
Checking for package HDF5... yes
Checking for package Python... yes
Checking for package PETSc... yes
Checking for package Numpy... yes
Checking for package Mpi4py... yes
Checking for package H5py... Can't find a built version of the h5py module ... building h5py  Building private h5py version at /Users/f/underworld2-2.0.3b/h5py
/opt/local/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'setup.py': [Errno 2] No such file or directory
/opt/local/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'setup.py': [Errno 2] No such file or directory
Failed building h5py :(
``` 
I prepared almost all other external dependency except the h5py, which I tried to install with `pip install h5py` but dose not work. Since h5py dependency is optional as mentioned in [COMPILE.md](https://github.com/underworldcode/underworld2/blob/master/COMPILE.md), can I just disable h5py? If so, how?

Best,
Qw

**Comment by jmansour** [comment]
Hi Qw

Did you use git to checkout Underworld2?  Or did you download a zip file?  This seems to be build system bug related to downloading the zip file.  

If you didn't can you try cloning underworld2 directly using git? 

```
git clone https://github.com/underworldcode/underworld2.git
```

Let us know if this helps.  

Also, sorry, on re-reading the COMPILE.md, it does indeed suggest that H5py is optional.  What we meant is that it's optional to have a system install of h5py, but if you don't, Underworld will download and compile its own version.  I'll update the documentation.

**Comment by QwZhang** [comment]
Hi jmansour, 
Thank you for your reply. 
I used the [source file](https://github.com/underworldcode/underworld2/releases) *Underworld2 pre-release 2.0.3-beta*. I also find that Underworld2 try to download and install a h5py if it is not available, but it is this h5py installed automatically failed to be found by UW2. I will try the code obtained through `git clone` again.

Best,
Qw

**Comment by QwZhang** [comment]
Hi jmansour, I use the source code obtained by `git clone` and run `./confugire.py` again but failed again:

```
$ ./configure.py --petsc-dir=/opt/local/petsc-3.4.5
scons: Reading SConscript files ...
Checking whether the C compiler worksyes
Checking for Solvers... yes
Checking for package libm... yes
Checking for package libXML2... yes
Checking for package MPI... yes
Checking for package HDF5... yes
Checking for package Python... yes
Checking for package PETSc... yes
Checking for package Numpy... yes
Checking for package Mpi4py... yes
Checking for package H5py... Can't find a built version of the h5py module ... building h5py  Building private h5py version at /Users/f/underworld2/h5py
running configure
Autodetected HDF5 1.10.0
********************************************************************************
                       Summary of the h5py configuration

    Path to HDF5: None
    HDF5 Version: '1.10.0'
     MPI Enabled: True
Rebuild Required: False

********************************************************************************
running build_ext
Autodetected HDF5 1.10.0
********************************************************************************
                       Summary of the h5py configuration

    Path to HDF5: None
    HDF5 Version: '1.10.0'
     MPI Enabled: True
Rebuild Required: False

********************************************************************************
Executing cythonize()
running build
running build_py
running build_ext
Autodetected HDF5 1.10.0
********************************************************************************
                       Summary of the h5py configuration

    Path to HDF5: None
    HDF5 Version: '1.10.0'
     MPI Enabled: True
Rebuild Required: False

********************************************************************************
Executing cythonize()
RuntimeError: Unable to import h5py module. It was possibly not build successfully.:
  File "/Users/f/underworld2/libUnderworld/SConfigure", line 196:
    env.ConfigurePackage(packages.H5py)
  File "/Users/f/underworld2/libUnderworld/config/scons/scons-local-1.2.0/SCons/Environment.py", line 217:
    return apply(self.method, nargs, kwargs)
  File "/Users/f/underworld2/libUnderworld/config/config.py", line 29:
    pkg(**kw)
  File "/Users/f/underworld2/libUnderworld/config/Package.py", line 148:
    for env in self.gen_envs(loc):
  File "/Users/f/underworld2/libUnderworld/config/packages/H5py.py", line 71:
    raise RuntimeError("Unable to import h5py module. It was possibly not build successfully.")
...
```
So it seems that h5py is still the cause of the problem:(. Perhaps I will have to prepare a well-working h5py separately.

Best,
Qw

**Comment by jmansour** [comment]
what happens when you try and import h5py from the **top level** underworld2 directory?
```
python -c "import h5py"
```

**Comment by QwZhang** [comment]
@jmansour Here it is:
```
$ python -c "import h5py"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named h5py```

**Comment by jmansour** [comment]
hmm, that's odd.  could be your version of 'pip' is at odds with your python interpreter.  can you try this:

```
$ python -c "import pip; pip.main(['install', 'six'])"
```

also, let us know the results for `which pip` and `which python`

**Comment by QwZhang** [comment]
Here it is: 
```
$ python -c "import pip; pip.main(['install', 'six'])"

Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named pip

$ which pip
/usr/local/bin/pip

$ which python
/opt/local/bin/python
```

**Comment by jmansour** [comment]
Hard to say exactly what has gone wrong here, but definitely looks like some python install conflict. I'd highly recommend using `virtualenv` as a cleaner method for using python on OS X. 

https://hackercodex.com/guide/python-development-environment-on-mac-osx/

Alternatively, save yourself all the compilation pain and use the docker version of Underworld2.  

http://www.underworldcode.org/posts/Underworld-and-Dockers
http://www.underworldcode.org/posts/Underworld-and-Dockers2

**Comment by QwZhang** [comment]
Many thanks!
