### ISSUE TITLE
docker image tests fail under `docker build`

### ISSUE THREAD

**Issue by jmansour** [underworldcode/underworld2#287]
So running the image tests interactively works fine:

```bash
docker pull underworldcode/underworld2_untested:dev
docker run underworldcode/underworld2_untested:dev /opt/underworld2/utils/run_tests.py /opt/underworld2/docs/test/image_tests.py
```

but when run from within `docker build` the image tests fail:
https://hub.docker.com/r/underworldcode/underworld2/builds/bmu4mtpgnpb42bzzdjsexaa/

Note that this failure can be reproduced locally by running `docker build`.  I've also attached an equivalent Dockerfile which ignores the `ERROR` signal so that the image is built regardless of issues. 

Building and running this Dockerfile, the error message from `image_tests.py` is

```bash
LavaVu Run error: Failed to open X display
```
and the standard out is
```bash
Failed to open X display

Traceback (most recent call last):
  File "image_tests.py", line 23, in <module>
    testmod = imp.load_source('runtest', modfile)
  File "/opt/underworld2/docs/test/image_tests/notebooks/runtest.py", line 59, in <module>
    lv.testimages(tolerance=1e-3)
  File "/opt/underworld2/glucifer/lavavu/lavavu.py", line 2299, in testimages
    results.append(self.testimage(expfile, outfile, tolerance))
  File "/opt/underworld2/glucifer/lavavu/lavavu.py", line 2336, in testimage
    raise RuntimeError("Generated image '%s' not found!" % outfile)
RuntimeError: Generated image './Figure_1.png' not found!
```
Though I'm guessing this final error is due to the X display issue. 

Any thoughts @OKaluza ?  Any recent changes you might suspect?  I'll note that we reverted our docker base image to one from around a year ago for the release, and this might be the first time it gets hit by the dev branch (as we just merged stable back into dev).  I'm about to update the base image to latest debian & packages, so it might possibly resolve the issue. 

[Dockerfile.tar.gz](https://github.com/underworldcode/underworld2/files/1897772/Dockerfile.tar.gz)

**Comment by jmansour** [comment]
Actually, I think the updated base image resolves this.  I'll close for now.
