### ISSUE TITLE
unit scaling in UW

### ISSUE THREAD

**Issue by RebeccaFarrington** [underworldcode/underworld2#290]
We should include pint and it's related dictionary into the next release of underworld.

**Comment by jmansour** [comment]
In uw27 now.

**Comment by tingyang2004** [comment]
So pint is a necessary dependency for UW2 now?
I am using scaling from Citcom. So is it possible that I do not include pint in my configuration?
I got the following error when running my script:
ImportError: No module named pint
Traceback (most recent call last):
  File "input7B.py", line 25, in <module>
    import underworld as uw
  File "/work/ess-yangt/UW2/Feb21/underworld2-2.7.1b/underworld/scaling/_scaling.py", line 16, in <module>
    from pint import UnitRegistry
    from pint import UnitRegistry
ImportError: No module named pint
    from pint import UnitRegistry
ImportError: No module named pint
  File "/work/ess-yangt/UW2/Feb21/underworld2-2.7.1b/underworld/__init__.py", line 57, in <module>
    from ._scaling import non_dimensionalise
  File "/work/ess-yangt/UW2/Feb21/underworld2-2.7.1b/underworld/scaling/_scaling.py", line 16, in <module>
ImportError: No module named pint
    import scaling as _scaling
  File "/work/ess-yangt/UW2/Feb21/underworld2-2.7.1b/underworld/scaling/__init__.py", line 14, in <module>
    from pint import UnitRegistry
ImportError:     from ._scaling import non_dimensionalise
  File "/work/ess-yangt/UW2/Feb21/underworld2-2.7.1b/underworld/scaling/_scaling.py", line 16, in <module>
No module named pint
    from pint import UnitRegistry
ImportError: No module named pint

**Comment by julesghub** [comment]
Yes, as of uw27 pint is a dependency. 
So it must be available on the system. But you don't have to use it.

You can install pint with `pip install --user pint`
