### ISSUE TITLE
xdmf save only takes mesh.save/SavedFileData not loaded file data

### ISSUE THREAD

**Issue by arijitlaik** [underworldcode/underworld2#346]
The typical use case being saving xdmf files after loading chcekpointed files from the disk, the xdmf save requires the meshHandle to be of a savedFileData, so there need to be a mesh.save(...) after a mesh.load(...)
as in
```python
restartFlag= True
if  restartFlag is True:
    mh=mesh.save(....)
else:
   mh=mesh.load(...)
...
...
solver.solve()
sfH=someField.save(...)
someField.xdmf(...,mh)
```
but something like this would result in this ValueError
```python Error
Traceback (most recent call last):
  File "mod_2d-v0.0.4low.py", line 777, in <module>
    checkpoint(step=0, time=dm(time, 1.*u.megayear).magnitude)
  File "mod_2d-v0.0.4low.py", line 259, in checkpoint
    velocityHnd, "velocity", meshHnd, "mesh", modeltime=time)
  File "/Users/arijit/underworld2/underworld/timing.py", line 320, in timed
    return routine(*args, **kwargs)
  File "/Users/arijit/underworld2/underworld/mesh/_meshvariable.py", line 293, in xdmf
    raise ValueError("'meshSavedData' must be of type SavedFileData")
ValueError: 'meshSavedData' must be of type SavedFileData
```

**Comment by arijitlaik** [comment]
?? please.

**Comment by rbeucher** [comment]
re-save the mesh?

**Comment by jmansour** [comment]
Yep, I agree, this is not great.  You can create the `SavedFileData` explicitly if you want:

```python
mh=mesh.load(...)
mesh_sfd = uw.utils.SavedFileData(mh, "your_mesh_checkpoint_file.h5")

solver.solve()
sfH=someField.save(...)
someField.xdmf("someField.xmf",sfH,"somefield",mesh_sfd,"mesh")
```
I haven't tested this, so give it a shot and let us know. 

https://underworld2.readthedocs.io/en/latest/underworld.utils.html#underworld.utils.SavedFileData

In the longer term, I'd like to redesign how we do all this, as it is quite clunky.

**Comment by rbeucher** [comment]
or create a SavedFileData

**Comment by rbeucher** [comment]
Oups sorry John

**Comment by arijitlaik** [comment]
thanks @jmansour  ill git the savedFileData a go

**Comment by arijitlaik** [comment]
Well it doesn't seem to work
```
  File "/Users/arijit/underworld2/underworld/timing.py", line 320, in timed
    return routine(*args, **kwargs)
  File "/Users/arijit/underworld2/underworld/mesh/_meshvariable.py", line 306, in xdmf
    raise RuntimeError("'meshSavedData file doesn't correspond to the object's mesh")
RuntimeError: 'meshSavedData file doesn't correspond to the object's mesh
```

**Comment by rbeucher** [comment]
Closing This. It needs a better design. UW3
