### ISSUE TITLE
Merry Xmas double free

### ISSUE THREAD

**Issue by julesghub** [underworldcode/underworld2#354]
If one runs the development docker.
Go into 
`./doc/test/image_tests/notebooks/01_GettingStarted`
and run 
`python3 01_GettingStarted.py`

a few times and errors occur.

Here is a sample
```
Thread 1 "python" hit Breakpoint 1, _MeshVariable_Destroy (meshVariable=0x5555566dbba0, data=0x0) at StgDomain/Mesh/src/MeshVariable.c:226
226	void _MeshVariable_Destroy( void* meshVariable, void* data ) {
(gdb) c
Continuing.

Thread 1 "python" hit Breakpoint 2, List_Remove (list=0x555556682080, data=data@entry=0x5555566dbba0) at StGermain/Base/Container/src/List.c:157
157	void List_Remove( void* list, void* data ) {
(gdb) c
Continuing.

Thread 1 "python" received signal SIGSEGV, Segmentation fault.
0x00007ffff6df6e48 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
(gdb) bt
#0  0x00007ffff6df6e48 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007fffe81e5ce9 in List_Remove (list=0x555556682080, data=data@entry=0x5555566dbba0) at StGermain/Base/Container/src/List.c:171
```

**Comment by julesghub** [comment]
Closing. This appears fixed.
