### ISSUE TITLE
Import Error (Underworld Dev)

### ISSUE THREAD

**Issue by tyszwh** [underworldcode/underworld2#374]
Underworld Dev Branch can be compiled correctly. But I found error when I import Underworld as uw.
In python3 
```
>>> import underworld as uw
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/3_10/underworld2dev_2019_3_10/underworld/__init__.py", line 83, in <module>
    import underworld.mesh
  File "/home/3_10/underworld2dev_2019_3_10/underworld/mesh/__init__.py", line 16, in <module>
    from ._meshvariable import MeshVariable
  File "/home/3_10/underworld2dev_2019_3_10/underworld/mesh/_meshvariable.py", line 13, in <module>
    from mpi4py import MPI
ImportError: /home/build/petsc-3.9.4/opt/lib/mpi4py/MPI.so: undefined symbol: _Py_ZeroStruct
>>> 

```

In python2

```
>>> import underworld as uw
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "underworld/__init__.py", line 50, in <module>
    import libUnderworld
  File "/home/3_10/underworld2dev_2019_3_10/libUnderworld/__init__.py", line 1, in <module>
    from .libUnderworldPy import *
  File "/home/3_10/underworld2dev_2019_3_10/libUnderworld/libUnderworldPy/__init__.py", line 2, in <module>
    from . import StGermain
  File "/home/3_10/underworld2dev_2019_3_10/libUnderworld/libUnderworldPy/StGermain.py", line 107
    def StgVariable_GetValueAtInt(arg1: '_StgVariable', arg2: 'unsigned int', arg3: 'unsigned int') -> "int":
                                      ^
SyntaxError: invalid syntax

How can I solve the problem?


```

**Comment by jmansour** [comment]
It looks like you've used PETSc to build your MPI4Py, however it is probably linked against your Py2 install (instead of Py3).  

Perhaps remove the PETSc installed version, and simply run `pip install mpi4py`.  (or `pip install --user mpi4py` if you only have user permissions).

**Comment by tyszwh** [comment]
Thanks, Jmansour. The problem is fixed.  It is the problem of mpi4py compiled from the petsc.
But the new error is occur when I try to import UWGeodynamics. 
```
>>> import UWGeodynamics as GEO
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/python3/lib/python3.7/site-packages/UWGeodynamics/__init__.py", line 575, in <module>
    if (underworld.rank() == 0) and not _in_doctest():
AttributeError: module 'underworld' has no attribute 'rank'
```
Besides the above problem, I found that the option like --python-dir=/user/local/python3/3.6.2 --with-debugging=0 can not be added with the configure.py. This problem is similar with "Checking for package NumpyPk when installing UW on the server #365". But I can't find the solution.

**Comment by jmansour** [comment]
You're version of UWGeo is out of sync with UW-dev.  @rbeucher? 

I'm a bit confused by your second issue... have you configured/built successfully?

**Comment by tyszwh** [comment]
The problem for importing the UWGeo is the version.

**Comment by rbeucher** [comment]
Actually UW and UWGeo are in sync which means if you use UW dev you need UWGeo Dev...

**Comment by tyszwh** [comment]
For the second problem, I can pass the configure.py as follows.

```
./configure.py --python-dir=/usr/local/python3/ --with-debugging=0
scons: Reading SConscript files ...
Checking whether the C compiler works... yes
Checking for Solvers... yes
Checking for package libm... yes
Checking for package libXML2... yes
Checking for package MPI... yes
Checking for package Python... yes
Checking for package PETSc... yes
IndexError: list index out of range:
  File "/home/3_10/underworld2dev_2019_3_10/libUnderworld/SConfigure", line 177:
    env.ConfigurePackage(packages.NumpyPk, required=True)
  File "/usr/local/python3/lib/python3.7/site-packages/scons/SCons/Environment.py", line 224:
    return self.method(*nargs, **kwargs)
  File "/home/3_10/underworld2dev_2019_3_10/libUnderworld/config/config.py", line 29:
    pkg(**kw)
  File "/home/3_10/underworld2dev_2019_3_10/libUnderworld/config/Package.py", line 150:
    for env in self.gen_envs(loc):
  File "/home/3_10/underworld2dev_2019_3_10/libUnderworld/config/packages/NumpyPk.py", line 32:
    env.AppendUnique(CPPPATH=[self.location[1][0]])
Checking for package NumpyPk... 
```

**Comment by tyszwh** [comment]
Yes, the first problem was my own mistake as I did not have synchronized version. @jmansour @rbeucher .

**Comment by jmansour** [comment]
But you have another configuration that works? Or is this a different machine you're having difficulties with? 

The message you posted is related to an error in the Numpy configuration script, but actually simply indicates that we couldn't configure against numpy.  Can you import numpy?

**Comment by tyszwh** [comment]
It is a same machine. The configuration works well without any options(just ./configure.py). And I can import Numpy. 
However, I can compile correctly without any additional options.

**Comment by jmansour** [comment]
So why do you need to specify additional options?  The `--with-debugging=0` option should certainly work regardless. 

If you wish to specify a particular Python install (via `--python-dir=...`), then ensure that you use the corresponding Python interpreter when you check that `numpy` is importable.

**Comment by tyszwh** [comment]
Ok, got it.
Yes, I try to choose specify a particular Python early. I will test this latter.
I close this problem for now.
