### ISSUE TITLE
Error evaluating 'map' function in high resolution regional spherical models

### ISSUE THREAD

**Issue by gthyagi** [underworldcode/underworld2#409]
Hi @julesghub @jmansour ,
I ran a models with (768, 1024, 256) resolution. During Stokes solve its displaying following error:
```python
Error message:
Error evaluating 'map' function.
Key function evaluates to key (1473834040) which
does not appear to map to any functions, and no default function has been set.
Traceback (most recent call last):
  File "/home/565/tg7098/res_test_annulus/2891_spherical/7681024256_sum_spherical.py", line 682, in <module>
    stokesSolver.solve(nonLinearIterate=True,callback_post_solve=postSolve)
  File "/short/n69/tg7098/Underworld/underworld2_reg_sph_debug/underworld/systems/_bsscr.py", line 427, in solve
    libUnderworld.StgFEM.SystemLinearEquations_MatrixSetup(self._stokesSLE._cself, None)
RuntimeError: Issue utilising function of class 'map' constructed at:
412- /home/565/tg7098/res_test_annulus/2891_spherical/7681024256_sum_spherical.py:426,
    viscosityFn = fn.branching.map( fn_key = materialVariable, mapping = viscosityMap )
```

I am attaching error file and python script
[7681024256_sum_spherical.txt](https://github.com/underworldcode/underworld2/files/3511487/7681024256_sum_spherical.txt)
[jobscript_pbs_o1273506.txt](https://github.com/underworldcode/underworld2/files/3511488/jobscript_pbs_o1273506.txt)
[jobscript_pbs_e1273506.txt](https://github.com/underworldcode/underworld2/files/3511489/jobscript_pbs_e1273506.txt)

**Comment by jmansour** [comment]
That's usually a problem that occurs because you have a particle which doesn't have a material index set on it.  In this case, a particle is reporting its material index is 1473834040.

**Comment by gthyagi** [comment]
@jmansour , thanks for confirming. Before creating different indices I am setting all values to zero (upper mantle material), with this all particles should be indexed. I will check matlab script once again and updates will be posted soon.

**Comment by gthyagi** [comment]
I am encountering this error only in (768, 1024, 256) resolution models.

**Comment by gthyagi** [comment]
@jmansour I double checked the values of material Variable h5 file (varies from 0 to 5) and all particles are indexed. But I am encountering this error while mapping viscosity. Model resolution is  (768, 1024, 256) and it contains 4 billion particles.

**Comment by jmansour** [comment]
Do you get the error if you don't reload the material index data, instead simply initialising all particles to `0`? 

Can you reproduce this issue at much smaller resolution and/or particle counts? 

You might need to post or email me your script. But simplify it as much as possible first please.

**Comment by gthyagi** [comment]
> Do you get the error if you don't reload the material index data, instead simply initialising all particles to `0`?
I will run a job now and let you know.

> Can you reproduce this issue at much smaller resolution and/or particle counts?
At smaller resolution I am not having this issue. It happens only in (768, 1024, 256) resolution models. I have one model with (512, 512, 256) resolution and every thing works normal in this model.

> You might need to post or email me your script. But simplify it as much as possible first please.
