### ISSUE TITLE
ImportError: No module named _StGermain

### ISSUE THREAD

**Issue by FifteenOUC** [underworldcode/underworld2#438]
Hi,
I've compiled libunderworld by `compile.sh` successfully and the file named `.build_success` exists. I've run the `updatePyPath.sh` file. 

However, there is an error when I import underworld in python. it seems python can not find _StGermain module. Does anyone know how to deal with it?

```python
[root@cu18 underworld2]# python
Python 2.7.5 (default, Aug  4 2017, 00:39:18) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-16)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import underworld
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "underworld/__init__.py", line 42, in <module>
    import libUnderworld
  File "/opt/sourcecode/underworld/NewFile2019.11.14/underworld2/libUnderworld/__init__.py", line 1, in <module>
    from libUnderworldPy import *
  File "/opt/sourcecode/underworld/NewFile2019.11.14/underworld2/libUnderworld/libUnderworldPy/__init__.py", line 2, in <module>
    import StGermain
  File "/opt/sourcecode/underworld/NewFile2019.11.14/underworld2/libUnderworld/libUnderworldPy/StGermain.py", line 21, in <module>
    _StGermain = swig_import_helper()
  File "/opt/sourcecode/underworld/NewFile2019.11.14/underworld2/libUnderworld/libUnderworldPy/StGermain.py", line 20, in swig_import_helper
    return importlib.import_module('_StGermain')
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named _StGermain
```

**Comment by julesghub** [comment]
Question:
What version of the Underworld are you compiling?

As of version Underworld-2.8.0b only python3 is supported. Your snippet above shows you have python-2.7.5.

Also worth mentioning is Underworld's docker image. It's much simpler to get started with UW using the container rather than compiling everything up. See here for details https://underworld2.readthedocs.io/en/latest/Installation.html

**Comment by FifteenOUC** [comment]
@julesghub Thanks for your reply! 

I have installed it by docker on MacOS. However, I want to install it in our HPC so that I have to do a native installation.

The Underworld version which I compiled is 2.7.1b. Is it OK? If Python3 is necessary, should I recompile everything or just install Python3?

**Comment by jmansour** [comment]
Yep you will need Python3 on the HPC.  Either locate or install it on the machine. You may or may not need to recompile Underworld.  

Let us know how you go.

**Comment by ponyby** [comment]
Hello! I have exactly the same problem. And I have Python version 3.7.1. I guess maybe it's something related to the path?

**Comment by julesghub** [comment]
Closing due to inactivity, feel free to reopen is you still have compiling issues.
