### ISSUE TITLE
Issue running Underworld import UWGeodynamics as GEO # there is a problem importing this - the script hangs

### ISSUE THREAD

**Issue by whositwhatnow** [underworldcode/underworld2#453]

**Comment by whositwhatnow** [comment]
I am having a heck of a time getting this to run below is the error i get trying to run my script and data to use the package.

Im using python 3.7.3 openmpi4.0.1 and petsc 3.11.4.

Traceback (most recent call last):
  File "drip-perlin-uwg.py", line 6, in <module>
    import UWGeodynamics as GEO # there is a problem importing this - the script hangs
  File "/cm/shared/apps/python/3.7.3b/lib/python3.7/site-packages/UWGeodynamics/__init__.py", line 44, in <module>
    from .LecodeIsostasy import LecodeIsostasy
  File "/cm/shared/apps/python/3.7.3b/lib/python3.7/site-packages/UWGeodynamics/LecodeIsostasy/__init__.py", line 2, in <module>
    from .LecodeIsostasy import LecodeIsostasy
  File "/cm/shared/apps/python/3.7.3b/lib/python3.7/site-packages/UWGeodynamics/LecodeIsostasy/LecodeIsostasy.py", line 6, in <module>
    from UWGeodynamics._material import Material
  File "/cm/shared/apps/python/3.7.3b/lib/python3.7/site-packages/UWGeodynamics/_material.py", line 24, in <module>
    class Material(object):
  File "/cm/shared/apps/python/3.7.3b/lib/python3.7/site-packages/UWGeodynamics/_material.py", line 43, in Material
    viscosityChangeX2=0.3, viscosityChange=1.0):
  File "/cm/shared/apps/python/3.7.3b/lib/python3.7/site-packages/pint/registry_helpers.py", line 329, in decorator
    % (func.__name__, count_params, len(dimensions))
TypeError: __init__ takes 24 parameters, but 1 dimensions were passed

**Comment by bknight1** [comment]
Hi @whositwhatnow,

I had the same issue, make sure you're using pint v0.9 instead of v0.10, and it should work.

**Comment by whositwhatnow** [comment]
OMG @bknight1 thanks i downgraded and it works now.

**Comment by jmansour** [comment]
Thanks @bknight1 & @whositwhatnow 

I'll start another ticket for the required `pint` updates.
