### ISSUE TITLE
mesh_aux.py fails for MPI enabled h5py 2.10.0

### ISSUE THREAD

**Issue by jmansour** [underworldcode/underworld2#487]
As per title. Non-mpi enabled version works fine. Can't see why there's a difference. 

```shell
root@uw-container:/workspace/uw2/docs/test# python mesh_aux.py 
        Global element size: 16x16
        Local offset of rank 0: 0x0
        Local range of rank 0: 16x16
Traceback (most recent call last):
  File "mesh_aux.py", line 63, in <module>
    meshtest(16,True)
  File "mesh_aux.py", line 32, in meshtest
    mesh.save('temp.h5')
  File "/workspace/uw2/underworld/mesh/_mesh.py", line 569, in save
    dset[self.data_nodegId[0:local],:] = self.data[0:local]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/opt/venv/lib/python3.7/site-packages/h5py/_hl/dataset.py", line 838, in __setitem__
    selection = sel.select(self.shape, args, dataset=self)
  File "/opt/venv/lib/python3.7/site-packages/h5py/_hl/selections.py", line 82, in select
    return selector.make_selection(args)
  File "h5py/_selector.pyx", line 264, in h5py._selector.Selector.make_selection
  File "h5py/_selector.pyx", line 173, in h5py._selector.Selector.apply_args
TypeError: Only 1D arrays allowed for fancy indexing
```

**Comment by julesghub** [comment]
I have made a release candidate docker image for uw-2.10. 
It's using parallel h5py-2.10 and mesh_aux.py runs fine.
The docker's hdf5 is version 1.10.5.

To get the docker:
 `docker pull underworldcode/underworld2:2.10.0b_rc`

**Comment by jmansour** [comment]
Interesting.  So any idea what's the difference from my failed runs?

**Comment by julesghub** [comment]
Nope. I suspect it's whatever env you were running under?

**Comment by jmansour** [comment]
Yep, tested your image and it works fine.  The image which generates this failure is `underworldcode/carbonite:petsc_dev`.  It appears to be running hdf5 1.10.6, though I'd be surprised if that'd make a difference.  

In any case, imma transfer this over to the uw3 repo.
