### ISSUE TITLE
One runtime error during restarting

### ISSUE THREAD

**Issue by Peigen-L** [underworldcode/underworld2#634]
**Hi underworld team,
I am running a 3D model on Gadi using version 2.10.0.
And I met a run time error during restarting I never met before. 
I restarted the model at 66 timestep and the model stopped at 74 timestep.
The error message shown as:**
>An uncaught exception was encountered on processor 375.
Traceback (most recent call last):
  File "./Seamount.py", line 544, in <module>
    Model.run_for(nstep=200, checkpoint_interval=2, restartStep=66, restartDir="/scratch/jq14/lp5029_model/Res/output_256x96x96/")
  File "/g/data/m18/codes/UWGeodynamics_2.10.2/lib/python3.7/site-packages/UWGeodynamics/_model.py", line 1635, in run_for
    self._update()
  File "/g/data/m18/codes/UWGeodynamics_2.10.2/lib/python3.7/site-packages/UWGeodynamics/_model.py", line 1744, in _update
    val.advector.integrate(dt)
  File "/g/data/m18/codes/UWGeodynamics_2.10.2/lib/python3.7/site-packages/underworld/systems/_timeintegration.py", line 152, in integrate
    super(SwarmAdvector,self).integrate(dt)
  File "/g/data/m18/codes/UWGeodynamics_2.10.2/lib/python3.7/site-packages/underworld/systems/_timeintegration.py", line 50, in integrate
    libUnderworld.StgDomain._TimeIntegrator_Execute(self._cself, None)
RuntimeError: Error encountered. Full restart recommended as exception safety not guaranteed. Error message:
Error - in TimeIntegrand_SecondOrder(), for TimeIntegrand "7UWF5FOA__integrand" of type SwarmAdvector: When trying to find time deriv for item 0 in step 1, *failed*.
>Unable to determine valid velocity for particle of local id 0 with coordinate (0.000000,0.000000,0.000000) on process rank 375. Coordinate appears to belong to another process's domain.

>An uncaught exception was encountered on processor 311.
Traceback (most recent call last):
  File "./Seamount.py", line 544, in <module>
    Model.run_for(nstep=200, checkpoint_interval=2, restartStep=66, restartDir="/scratch/jq14/lp5029_model/Res/output_256x96x96/")
  File "/g/data/m18/codes/UWGeodynamics_2.10.2/lib/python3.7/site-packages/UWGeodynamics/_model.py", line 1635, in run_for
    self._update()
  File "/g/data/m18/codes/UWGeodynamics_2.10.2/lib/python3.7/site-packages/UWGeodynamics/_model.py", line 1744, in _update
    val.advector.integrate(dt)
  File "/g/data/m18/codes/UWGeodynamics_2.10.2/lib/python3.7/site-packages/underworld/systems/_timeintegration.py", line 152, in integrate
    super(SwarmAdvector,self).integrate(dt)
  File "/g/data/m18/codes/UWGeodynamics_2.10.2/lib/python3.7/site-packages/underworld/systems/_timeintegration.py", line 50, in integrate
    libUnderworld.StgDomain._TimeIntegrator_Execute(self._cself, None)
RuntimeError: Error encountered. Full restart recommended as exception safety not guaranteed. Error message:
Error - in TimeIntegrand_SecondOrder(), for TimeIntegrand "XOIRSI74__integrand" of type SwarmAdvector: When trying to find time deriv for item 0 in step 1, *failed*.
>Unable to determine valid velocity for particle of local id 0 with coordinate (0.000000,0.000000,0.000000) on process rank 311. Coordinate appears to be outside the global domain.

**Then I tried restarting again at 73 timestep, and the model running stopped at timestep 74 and recalled the error message again**

>An uncaught exception was encountered on processor 375.
Traceback (most recent call last):
  File "./Seamount.py", line 544, in <module>
    Model.run_for(nstep=200, checkpoint_interval=2, restartStep=73, restartDir="/scratch/jq14/lp5029_model/Res/output_256x96x96/")
  File "/g/data/m18/codes/UWGeodynamics_2.10.2/lib/python3.7/site-packages/UWGeodynamics/_model.py", line 1635, in run_for
    self._update()
  File "/g/data/m18/codes/UWGeodynamics_2.10.2/lib/python3.7/site-packages/UWGeodynamics/_model.py", line 1744, in _update
    val.advector.integrate(dt)
  File "/g/data/m18/codes/UWGeodynamics_2.10.2/lib/python3.7/site-packages/underworld/systems/_timeintegration.py", line 152, in integrate
    super(SwarmAdvector,self).integrate(dt)
  File "/g/data/m18/codes/UWGeodynamics_2.10.2/lib/python3.7/site-packages/underworld/systems/_timeintegration.py", line 50, in integrate
    libUnderworld.StgDomain._TimeIntegrator_Execute(self._cself, None)
RuntimeError: Error encountered. Full restart recommended as exception safety not guaranteed. Error message:
Error - in TimeIntegrand_SecondOrder(), for TimeIntegrand "EXRCMURR__integrand" of type SwarmAdvector: When trying to find time deriv for item 0 in step 1, *failed*.
Unable to determine valid velocity for particle of local id 0 with coordinate (0.000000,0.000000,0.000000) on process rank 375. Coordinate appears to belong to another process's domain. 

Please help

Kind regards

Peigen

**Comment by Peigen-L** [comment]
Please find the codes/pbs/running log/error massage through[https://github.com/underworld-community/Peigen-HPC]

**Comment by julesghub** [comment]
Hi @Peigen-L ,

I see the error
```
Error - in TimeIntegrand_SecondOrder(), for TimeIntegrand "7UWF5FOA__integrand" of type SwarmAdvector: When trying to find time deriv for item 0 in step 1, *failed*.

Unable to determine valid velocity for particle of local id 0 with coordinate (0.000000,0.000000,0.000000) on process rank 375. Coordinate appears to belong to another process's domain.
An uncaught exception was encountered on processor 311.
```
this indicates _a swarm_ has particles that are doing something unexpected near the boundary of the mesh. 
Do you understand if the fluid flow is well behaved near the boundaries, can you visualise the flow?

I see you're using tracers swarms. Does the problem go away if you remove / comment out the tracer swarms and try the restart?

cheers,
J

**Comment by Peigen-L** [comment]
Hi @julesghub 

I removed the tracer swarm and problem went away after that. Thanks.

Kind regards
Peigen

**Comment by julesghub** [comment]
Ok great to know. Tracers around the boundary of the mesh can cause problems.
