### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by qmpotential** [underworldcode/underworld2#687]
Hey guys,

Just followed the installation guide and got the following error. Can someone help me with that?

  File "<string>", line 137, in run
    File "<string>", line 240, in build_extension
    File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['cmake', '-S', '/tmp/pip-req-build-6tpp9_cg/underworld/libUnderworld', '-B', '/tmp/pip-req-build-6tpp9_cg/build/temp.linux-x86_64-cpython-310_libUnderworld', '-GNinja', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_INSTALL_PREFIX:PATH=/tmp/pip-req-build-6tpp9_cg/build/lib.linux-x86_64-cpython-310/underworld', '-DPython3_ROOT_DIR=/usr', '-DCALL_FROM_SETUP_PY:BOOL=ON']' returned non-zero exit status 1.
  error: subprocess-exited-with-error
  
  × Building wheel for underworld (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /usr/bin/python3 /usr/local/lib/python3.10/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py build_wheel /tmp/tmpa33ef2yf
  cwd: /tmp/pip-req-build-6tpp9_cg
  Building wheel for underworld (pyproject.toml) ... error
  ERROR: Failed building wheel for underworld
Failed to build underworld
ERROR: Could not build wheels for underworld, which is required to install pyproject.toml-based projects

**Comment by julesghub** [comment]
Hi @qmpotential,

I can't make out the error from this log, is there more output information available. If so, please send it through.
Also what version of the code are you installing from source? Which git revision?

Another strategy to overcome this is to use the Underworld2's container images. You could use `podman` (preferred container software) or `docker` to quickly spin up an Underworld2 instance.
See - https://hub.docker.com/r/underworldcode/underworld2/tags for the available versions. Note the `podman` / `docker` commands can be used interchangeably for Underworld usage. 

Hope this help.

**Comment by qmpotential** [comment]
Thank you so much for such a quick response. I've tried to follow the installation instructions on using pip.
https://github.com/underworldcode/underworld2/blob/master/Installation.rst

You can install Underworld using pip as follows:
pip underworld2
Unfortunately, it is a little bit confusing since pip underworld2 does to work for me.

Trying to resolve that with the git version gives me the above mistake.
pip install -v git+https://github.com/underworldcode/underworld2

I do not want to use docker at this moment and I was wondering if I can just install it without 
a container.

**Comment by julesghub** [comment]
Thanks for letting us know  `pip install underworld` command isn't working.

Underworld can't build on platforms like Colab because our dependency code, PETSc doesn't build on colab.
Hence why we have the container solution which works well on other cloud platforms.

Are you wanting to build the code on a local machine? How are you wanting to use it?

Make sure you have petsc installed and the environment variable `PETSC_DIR`  pointing to the installation.
Here's some general information about it https://www.underworldcode.org/setting-up-underworld-dependencies/
Note: The PETSc version is old in the link. The latest underworld runs on petsc-3.19.

**Comment by qmpotential** [comment]
Thank you so much! 

I tried to install it on the local machine and HPC and got the same error as from Colab.
Using pip install -v git+https://github.com/underworldcode/underworld2 results in an ERROR
posted before. Thank you for the PETSc information, I will try petsc-3.19 version.

I will try a container today and let you know how that works.

Sincerely,

**Comment by qmpotential** [comment]
When trying to install on the Linux( RHEL8) desktop I am getting the following:

linux-x86_64-cpython-39/src/dynload.o
      src/dynload.c:5:10: fatal error: Python.h: No such file or directory
       #include "Python.h"
                ^~~~~~~~~~
      compilation terminated.
      warning: build_ext: command '/usr/bin/gcc' failed with exit code 1
      
      warning: build_ext: building optional extension "mpi4py.dl" failed

**Comment by julesghub** [comment]
Try install the python development header.

Something like
`yum -y install python-devel`

That will include "Python.h"

**Comment by qmpotential** [comment]
When trying to install on the Linux( RHEL8) desktop I am getting the following:

linux-x86_64-cpython-39/src/dynload.o
      src/dynload.c:5:10: fatal error: Python.h: No such file or directory
       #include "Python.h"
                ^~~~~~~~~~
      compilation terminated.
      warning: build_ext: command '/usr/bin/gcc' failed with exit code 1
      
      warning: build_ext: building optional extension "mpi4py.dl" failed

**Comment by qmpotential** [comment]
Thank you so much to all! The Pyhton.h has been cleared, no mistakes any more.
However, I've got another one while trying to install mpi4py.

    gcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python3.6m -c _configtest.c -o _configtest.o
    _configtest.c:2:10: fatal error: mpi.h: No such file or directory
     #include <mpi.h>
              ^~~~~~~
    compilation terminated.
    failure.
    removing: _configtest.c _configtest.o
    error: Cannot compile MPI programs. Check your configuration!!!
    
    ----------------------------------------
Command "/usr/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-wdae79m2/mpi4py/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-k7jmulrv-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-wdae79m2/mpi4py/

**Comment by julesghub** [comment]
Hi Oleg,

Now you're missing the development header for an MPI implementation.
Try something like
`sudo yum install openmpi` 
to install it.

All Underworld2 build dependencies packages are listed here. 
https://github.com/underworldcode/underworld2/blob/master/Installation.rst#build-environment

Also there is this guide to installing most of those dependencies under Ubuntu. Although you're on RHEL it will still be helpful. https://www.underworldcode.org/setting-up-underworld-dependencies/

**Comment by qmpotential** [comment]
Thank you so much, for some reason it does not work.
I've installed that already but it still can not find it.

**Comment by julesghub** [comment]
I'm not familiar with RHEL8 packages unfortunately.
What `openmpi` or `mpich` development packages can you install with RHEL8?

E.g. `sudo yum install openmpi-devel`

**Comment by qmpotential** [comment]
Hey, Guys,

Thank you so much for all your help. I am still struggling with the installation. I am attaching the entire installation/compilation stderr file. I appreciate any help with that. 

[installation_underworld.txt](https://github.com/underworldcode/underworld2/files/14241473/installation_underworld.txt)

**Comment by qmpotential** [comment]
> Hi @qmpotential,
> 
> Would it be convenient for you to provide complete compilation error information? Sending all installation results to a file instead of a screen may better solve the problem.
> 
> N.

[installation_underworld.txt](https://github.com/underworldcode/underworld2/files/14241553/installation_underworld.txt)

**Comment by julesghub** [comment]
The python package `ninja` is not being found
```
  CMake Error at CMakeLists.txt:7 (project):
    Running

     '/home/olegsupp/.local/bin/ninja' '--version'

    failed with:

     Traceback (most recent call last):
      File "/home/olegsupp/.local/bin/ninja", line 5, in <module>
        from ninja import ninja

    ModuleNotFoundError: No module named 'ninja'
```
Run
`pip install ninja`



For a complete list of build requirements, both programs and python packages, for the current docker image see here.
https://github.com/underworldcode/underworld2/blob/e62b5de9a5ba673b6df23c94f4f6f34e34a301d7/docs/development/docker/underworld2/Dockerfile#L83

I'll update the code to ensure `ninja` is a requirement in the build phase.
We are getting close to an install.

**Comment by qmpotential** [comment]
Dear Julian,

The problem is that I've installed ninja, mpi, and ... It still gives me that error that those packages can not be found.

**Comment by julesghub** [comment]
What is the new error exactly?  A log file would be useful.

You can check if you've installed ninja and mpi as follows
`ninja --version`
`mpicc --show`

Did you have any luck using the docker solution?

**Comment by qmpotential** [comment]
Here is the entire installation log.
[underworld.txt](https://github.com/underworldcode/underworld2/files/14334043/underworld.txt)
Sincerely,

**Comment by qmpotential** [comment]
ninja --version
1.11.1.git.kitware.jobserver-1

**Comment by qmpotential** [comment]
Can I install it via the Conda environment somehow?

**Comment by NTIaN7** [comment]
> Can I install it via the Conda environment somehow?

Hi @qmpotential 
These issues should be caused by environmental dependence. Personally, I would recommend using the Intel MPI suite to compile PETSc and using Conda to manage the Python environment and its dependencies. I do not recommend using OpenMPI or MPICH and PETSc installed by Conda as their performance may be poor.

N.

**Comment by NTIaN7** [comment]
@qmpotential 
Congratulations! The installation seemed smooth this time. But one thing worth noting is that h5py is automatically installed as a dependency of underworld2 and is usually only serial. It can be detected through the following code, `True` means parallel support:
```python
conda activate xxx
import h5py
h5py.get_config().mpi
```
You can refer [here](https://underworld2.readthedocs.io/en/latest/Installation.html) to install h5py that supports parallel IO.
```bash
CC=mpicc HDF5_MPI="ON" HDF5_DIR=/path/to/your/hdf5/install/ pip install --no-binary=h5py h5py
```

**Comment by qmpotential** [comment]
@NTIaN7 

That is great! Thank you so much for the notice. I will try that and get back to you!
